## Builds a logical matrix of presence/absence TSS data from data generated by buildGeneDb()

library(rtracklayer)

createGenePresenceMa <- function(geneDb, tssDb) {
	    if (is.list(geneDb)==FALSE) {
	       stop("geneDb must be of class 'list'")
	       }

	    if (is.list(tssDb)==FALSE) {
	       stop("tssDb must be of class 'list'")
	       }

	    message("Calculating matrix of presence/absence from tss and geneDbs.")

	    gDb.len <- length(names(geneDb))
	    print(gDb.len)
	    tDb.len <- length(names(tssDb))

	    if (gDb.len != tDb.len) {
	       stop("geneDb and tssDb files must be of the same length")
	       }	       

	    #continue here:

	    my.list <- vector(mode="list", length=tDb.len)
	    my.slots <- sort(names(tssDb))
	    print(my.slots)
	    x <- length(my.slots)
	    #print(head(my.slots)) #for debugging
	    names(my.list) <- my.slots
	         for (i in my.slots) {
		      tss.genes <- names(tssDb[[i]])
		      all.genes <- geneDb[[i]]
		      this.match <- match(all.genes, tss.genes)
		      my.list[[i]] <- this.match
		      }

	   return(my.list)
}
