; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                = 10200331-x86_64 macOS             
[ DataSettings ]
datatype                           = snNucleotide                      
containsCodingNuc                  = False                             
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
Labelled Sites                     = All Sites                         
Labels to Include                  =                                   
[ ProcessTypes ]
ppDistEst                          = true                              
ppPairTaxa                         = true                              
[ AnalysisSettings ]
Analysis                           = Distance Estimation               
Scope                              = Pairs of taxa                     
Estimate Variance                  = ====================              
Variance Estimation Method         = None                              
No. of Bootstrap Replications      = Not Applicable                    
Substitution Model                 = ====================              
Substitutions Type                 = Nucleotide                        
Model/Method                       = Jukes-Cantor model                
Substitutions to Include           = All                               
Rates and Patterns                 = ====================              
Rates among Sites                  = Uniform Rates                     
Gamma Parameter                    = Not Applicable                    
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Pairwise deletion                 
Site Coverage Cutoff (%)           = Not Applicable                    
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
