## Builds a logical matrix of presence/absence TSS data from data generated by buildGeneDb()

library(rtracklayer)

buildGeneDb <- function(geneDb, tssDb) {
	    if (is.list(geneDb)==FALSE) {
	       stop("geneDb must be of class 'list'")
	       }

	    if (is.list(tssDb)==FALSE) {
	       stop("tssDb must be of class 'list'")
	       }

	    message("Calculating .")

	    gDb.len <- length(names(geneDb))
	    tDb.len <- length(names(tssDb))

	    if (gDb.len != tDb.len) {
	       stop("geneDb and tssDb files must be of the same length")
	       }	       

	    #continue here:

            my.seq <- 1:x
	    my.list <- vector(mode="list", length=x)
	    my.slots <- speciesNames
	    #print(my.slots) #for debugging
	    names(my.list) <- my.slots
	    #print(names(my.list)) #for debugging
	         for (i in 1:x) {
	              this.gff  <- readGFF(filepath=x.1[[i]])
		      this.df <- this.gff[this.gff$type=="gene",]
		      genes.table <- this.df$ID
		      my.list[[i]] <- genes.table
		      }

	   return(my.list)
}
