## Builds a logical matrix of presence/absence TSS data from data generated by buildGeneDb()

library(rtracklayer)

isPresentOP <- function(opDb, tssDb, sppIDs) {
	    if (is.list(geneDb)==FALSE) {
	       stop("geneDb must be of class 'list'")
	       }

	    if (is.list(tssDb)==FALSE) {
	       stop("tssDb must be of class 'list'")
	       }

	    if (is.character(sppIDs)==FALSE) {
	       stop("sppIDs must be of class 'character'")
	       }

	    message("Generating table of OP presence-absence using tssDb and opDb.")

	    #continue here:

	    sp.len <- length(sppIDs)

	    my.matrix <- matrix(NA, nrow=length(names(opDb)), ncol=length(sppIDs))
	    print(my.slots)
	         for (i in length(names(opDb))) {
		      #continue here
		      }

	   return(my.list)
}
