## Builds a logical matrix of presence/absence TSS data from data generated by buildGeneDb()

library(rtracklayer)

isPresentOP <- function(opDb, tssDb, sppIDs) {
	    if (is.list(geneDb)==FALSE) {
	       stop("geneDb must be of class 'list'")
	       }

	    if (is.list(tssDb)==FALSE) {
	       stop("tssDb must be of class 'list'")
	       }

	    if (is.character(sppIDs)==FALSE) {
	       stop("sppIDs must be of class 'character'")
	       }

	    message("Generating table of OP presence-absence using tssDb and opDb.")

	    #continue here:

	    my.OP <- unlist(opDb)
	    my.OP.n <- gsub(".G", ".P", my.OP)
	    my.matrix <- matrix(my.OP.n, nrow=length(names(opDb)), ncol=28, byrow=FALSE) 

            colnames(my.matrix) <- c("Pbi.1", "Pbi.2", "Pdec.1", "Pdec.2", "Pdodec.1", "Pdodec.2", "Pjenn.1", "Pjenn.2", "Pnov.1", "Pnov.2", "Poct.1", "Poct.2", "Ppent.1", "Ppent.2", "Pprim.1", "Pprim.2", "Pquad.1", "Pquad.2", "Psept.1", "Psept.2", "Psex.1", "Psex.2", "Pson.1", "Pson.2", "Ptet.1", "Ptet.2", "Ptre.1", "Ptre.2")

	    my.cols <- colnames(my.matrix)

	    col.matches <- unique(grep(paste(sppIDs,collapse="|"), 
                        colnames(my.matrix), value=TRUE))

	    #print(head(col.matches))

            this.match <- match(col.matches, my.cols)
	    #print(this.match)	    

	    print(head(my.matrix))

	    reduced.ma <- my.matrix[,na.omit(this.match)]
	    #print(head(reduced.ma))
	    ## problem: reduced.ma is not being populated properly
	    
	         for (i in 1:length(names(tssDb))) {
		      print(i)
		      this.name <- names(tssDb)[i]
		      print(this.name)
		      this.vec <- names(tssDb[[this.name]])
		      print(head(this.vec))
		      #print(opDb[[this.name]])
		      ## continue with loop here to fill in the matches
#		      #vec.match <- match(this.vec, opDb[[this.name]])
		      #print(head(vec.match))
		      }

	   return(my.matrix)
}
